spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: Root
    url: jdbc:mysql://localhost:3306/blogDB?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
  thymeleaf:
    cache: false
debug: true



